# Generated by Django 6.0 on 2025-12-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('exam_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Filled', 'Filled'), ('Completed', 'Completed')], default='Open', max_length=10)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Requester', 'Requester'), ('Scribe', 'Scribe')], max_length=10)),
                ('academic_level', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('exam_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examrequest')),
            ],
            options={
                'unique_together': {('scribe', 'exam_request')},
            },
        ),
    ]
